MorishitaAssignments/Models/Assignments.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace MorishitaAssignments.Models
{
    public class Assignments
    {
        [Key]
        public int AssignmentId { get; set; }

        [Required]
        public string AssignmentName { get; set; } = string.Empty;
        [Required]
        public string Link { get; set; } = string.Empty;

        // a read-only property for the slug at the end of the URL
        public string Slug => AssignmentName.ToString();
    }
}

MorishitaAssignments/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace MorishitaAssignments.Models
{
    public class Student
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string FirstName { get; set; } = string.Empty;
        [Required]
        public string LastName { get; set; } = string.Empty;
        [Required]
        public string Grade { get; set; } = string.Empty;
        [Required]
        public int StudentAccessLevel { get; set; } = 0;
    }
}

MorishitaAssignments/Models/StudentContext.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MorishitaAssignments.Models
{
    public class StudentContext : DbContext
    {
        public StudentContext(DbContextOptions<StudentContext> options) : base(options)
        { }

        public DbSet<Student> Students { get; set; } = null!;
        public DbSet<Assignments> Assigns { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Assignments>().HasData(
                new Assignments
                {
                    AssignmentId = 1,
                    AssignmentName = "Assignment 6.1",
                }
                );

            modelBuilder.Entity<Assignments>().HasData(
               new Assignments
               {
                   AssignmentId = 2,
                   AssignmentName = "Assignment 7.1",
               }
               );

            modelBuilder.Entity<Assignments>().HasData(
              new Assignments
              {
                  AssignmentId = 3,
                  AssignmentName = "Assignment 8.5",
              }
              );

            modelBuilder.Entity<Student>().HasData(
              new Student
              {
                  Id = 1,
                  FirstName = "Sharean",
                  LastName = "Vesey",
                  Grade = "12",
                  StudentAccessLevel = 9
              }
              ); ;

            modelBuilder.Entity<Student>().HasData(
            new Student
            {
                Id = 2,
                FirstName = "Dewayne",
                LastName = "Mori",
                Grade = "9",
                StudentAccessLevel = 6
            }
            );

            modelBuilder.Entity<Student>().HasData(
            new Student
            {
                Id = 3,
                FirstName = "Esiah",
                LastName = "Lonnell",
                Grade = "9",
                StudentAccessLevel = 6
            }
            );

            modelBuilder.Entity<Student>().HasData(
            new Student
            {
                Id = 4,
                FirstName = "Elizabeth",
                LastName = "Shalonda",
                Grade = "8",
                StudentAccessLevel = 2
            }
            );
        }
    }
}

MorishitaAssignments/Controllers/AssignmentsController.cs
using Microsoft.AspNetCore.Mvc;
using MorishitaAssignments.Models;


namespace MorishitaAssignments.Controllers
{
    public class AssignmentsController : Controller
    {
        public StudentContext context { get; set; }

        public AssignmentsController(StudentContext ctx) => context = ctx;

        [HttpGet]
        public IActionResult Assignments()
        {
            var assign = context.Assigns.OrderBy(r => r.AssignmentId).ToList();
            return View(assign);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            //ViewBag.AssignmentIds = context.Assigns.ToList();
            Assignments assignments = context.Assigns.Where(a => a.AssignmentId == id).FirstOrDefault() ?? new Assignments();
            return View(assignments);
        }
    }
}

MorishitaAssignments/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MorishitaAssignments.Models;
using System.Diagnostics;

namespace MorishitaAssignments.Controllers
{
    public class HomeController : Controller
    {
        public StudentContext context { get; set; }

        public HomeController(StudentContext ctx) => context = ctx;

        [HttpGet]
        public IActionResult Index()
        {
            
            return View();
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

    }
}

MorishitaAssignments/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MorishitaAssignments.Models;

namespace MorishitaAssignments.Controllers
{
    public class StudentController : Controller
    {
        public StudentContext context { get; set; }

        public StudentController(StudentContext ctx) => context = ctx;

        [HttpGet]
        public IActionResult Students()
        {
            ViewBag.Access = 9; // This determines the students routing access
            var student = context.Students.OrderBy(s => s.Id).ToList();
            return View(student);
        }
    }
}

MorishitaAssignments/Views/Assignments/Assignments.cshtml
@model List<Assignments>
@{ViewData["Title"] = "Assignments Page";}

<!--
    Author: Elijah Morishita
    Date: 7/4/2023
    Assignments Page
-->


    <br>
    <br>
    <br>
    <div class="row">
        <div class="col"><!--col 1-->
        <h2>Assignments</h2>
        </div><!--Close col-->
    </div><!--close row-->
            
    <div class="row">
        <div class="col"><!--col 1-->
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th>AssignmentId</th>
                    <th>AssignmentName</th>
                    <th>Link</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var AssignItem in Model)
                    {
                        <tr>
                        <td>@AssignItem.AssignmentId</td>
                        <td>@AssignItem.AssignmentName</td>
                        <td>@AssignItem.Link</td>
                            <td>
                                <a asp-controller="Assignments" asp-action="Details" asp-route-id="@AssignItem.AssignmentId" asp-route-slug="@AssignItem.Slug">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div><!--Close col-->
    </div><!--close row-->

    <br>
    <br>
    <br>

MorishitaAssignments/Views/Assignments/AssignmentsHome.cshtml
@model List<Assignments>
@{ViewData["Title"] = "Assignments Page";}

<!--
    Author: Elijah Morishita
    Date: 7/4/2023
    Assignments Page
-->
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col"><!--col 1-->
        <h2>Assignments</h2>
        </div><!--Close col-->
    </div><!--close row-->
            
    <div class="row">
        <div class="col"><!--col 1-->
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th>AssignmentId</th>
                    <th>AssignmentName</th>
                    <th>AccessLevel</th>
                    <th>Link</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var AssignItem in Model)
                    {
                        <tr>
                        <td>@AssignItem.AssignmentId</td>
                        <td>@AssignItem.AssignmentName</td>
                        <td>@AssignItem.AccessLevel</td>
                        <td>@AssignItem.Link</td>
                            <td>
                            <a asp-controller="Assignments" asp-action="Details" asp-route-id="@AssignItem.AssignmentId" asp-route-slug="@AssignItem.Slug">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div><!--Close col-->
    </div><!--close row-->

    <br>
    <br>
    <br>

MorishitaAssignments/Views/Assignments/Details.cshtml
@model Assignments
@{
    ViewData["Title"] = "Assignments Page";
}


<!--
    Author: Elijah Morishita
    Date: 7/4/2023
    Assignments Page
-->

<br>
<br>
<br>

<div class="row">
    <div class="col">
        <!--col 1-->
        <div class="mb-2">
            <h2>@Model.AssignmentName</h2>
        </div>
    </div><!--Close col-->
</div><!--close row-->

<div class="row">
    <div class="col">
        <!--col 1-->
        <div>ID: @Model.AssignmentId</div>
        <div>Assingment: @Model.AssignmentName</div>
        <div><a href=" ../../../.. /../Student/Students">Students</a></div>
        <br>
        <a asp-controller="Assignments" asp-action="Assignments">Assignments Home</a>
    </div><!--Close col-->
</div><!--close row-->

<br>
<br>
<br>

MorishitaAssignments/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To</h1>
    <p>Elijah Morishita's Assignments Page</p>
</div>

MorishitaAssignments/Views/Shared/_AccessOneLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Morishita Assignments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MorishitaAssignments.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MorishitaAssignments - Lower Access</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <select onChange="window.location.href=this.value">
                                <option value="" selected disabled>Assignments</option>
                                <option value="../../Assignments/Assignments">Assignment 6.1</option>
                            </select>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MorishitaAssignments
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MorishitaAssignments/Views/Shared/_AccessThreeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Morishita Assignments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MorishitaAssignments.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MorishitaAssignments - Admin Access</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <select onChange="window.location.href=this.value">
                                <option value="" selected disabled>Assignments</option>
                                <option value="../../Assignments/Assignments">Assignment 6.1</option>
                            </select>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MorishitaAssignments
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MorishitaAssignments/Views/Shared/_AccessTwoLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Morishita Assignments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MorishitaAssignments.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MorishitaAssignments - MidAccess</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <select onChange="window.location.href=this.value">
                                <option value="" selected disabled>Assignments</option>
                                <option value="../../Assignments/Assignments">Assignment 6.1</option>
                            </select>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MorishitaAssignments
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MorishitaAssignments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Morishita Assignments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MorishitaAssignments.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MorishitaAssignments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Students">Students</a>
                        </li>
                        <li>
                            <select onChange="window.location.href=this.value">
                                <option value=""></option>
                                <option value="../../Assignments/Assignments">Assignment 6.1</option>
                            </select>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MorishitaAssignments 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MorishitaAssignments/Views/Student/Students.cshtml
@model List<Student>
@{
    ViewData["Title"] = "Students Page";
}

<!--
    Author: Elijah Morishita
    Date: 7/4/2023
    Assignments Page
-->
<br>
<br>
<br>
<div class="row">
    <div class="col">
        <!--col 1-->
        @{
            if(ViewBag.Access < 2){
                <h2>"Students - You do not have a sufficient access level to view this data"</h2>
                <p>Your current access level is: @ViewBag.Access</p>
                Layout = "_AccessOneLayout";
            }
            else
            {
                <h2>Students</h2>
                <p>Your current access level is: @ViewBag.Access</p>
                Layout = "_AccessTwoLayout";
                if (ViewBag.Access >= 8){
                    <h4>Welcome Admin</h4>
                    Layout = "_AccessThreeLayout";
                }
            }
        }
        
    </div><!--Close col-->
</div><!--close row-->

<div class="row">
    <div class="col">
        <!--col 1-->
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Student ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var StudentItem in Model)
                {
                    <tr>
                        <td>@StudentItem.Id</td>
                        @{
                           
                            if (ViewBag.Access >= 2 && ViewBag.Access < 8)
                            {
                                <td>@StudentItem.FirstName</td>
                                <td>@StudentItem.LastName</td>
                            }
                            if (ViewBag.Access > 8)
                            {
                                <td>@StudentItem.FirstName</td>
                                <td>@StudentItem.LastName</td>
                                <td>@StudentItem.Grade</td>
                            }
                        }
                        
                        
                    </tr>
                }
            </tbody>
        </table>
    </div><!--Close col-->
</div><!--close row-->

<br>
<br>
<br>